services:
  - type: web
    name: react-spa
    env: static
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        staticPublishPath: dist
